version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: mentei_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sosederbele
      POSTGRES_DB: mentei_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 